# Makefile for string_example.c

CC = gcc
CFLAGS = -Wall -Wextra
TARGET = string_example

all: $(TARGET)

$(TARGET): string_example.c
	$(CC) $(CFLAGS) -o $(TARGET) string_example.c

clean:
	rm -f $(TARGET)
